services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_ENV: docker
    ports:
      - "3000:80"
    env_file:
      - .env.docker
    # จำกัดการใช้ memory สูงสุดไม่เกิน 128MB เพื่อลดการใช้ทรัพยากร
    mem_limit: 128M
    mem_reservation: 64M
    restart: unless-stopped
    networks:
      - go-fullstack-network

networks:
  go-fullstack-network: