apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: go-fullstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # ถ้ามี storageClassName เฉพาะ ให้ระบุตรงนี้
  # storageClassName: standard
