services:
  backend:
    image: backend:${BACKEND_VERSION}
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    # จำกัดการใช้ memory สูงสุดไม่เกิน 256MB เพื่อลดการใช้ทรัพยากร
    mem_limit: 256M
    mem_reservation: 128M
    restart: unless-stopped
    networks:
      - go-fullstack-network

networks:
  go-fullstack-network: