apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: go-fullstack
type: Opaque
stringData:
  # เปลี่ยน credentials เหล่านี้ใน production
  root-user: minioadmin
  root-password: miniopassword
