[SERVICE]
    Flush        1
    Log_Level   info
    Parsers_File parsers.conf

[INPUT]
    Name   tail
    Path   /var/lib/docker/containers/*/*-json.log
    Parser docker
    Tag    docker

[OUTPUT]
    Name                es
    Match               *
    Host                elasticsearch
    Port                9200
    Index               docker-logs
    Logstash_Format     On
    Logstash_Prefix     docker-logs
    Suppress_Type_Name  On
    Generate_ID         On
    Retry_Limit         False